import { createContext, useContext, useEffect, useMemo, useState } from "react";

const LanguageContext = createContext(null);
const STORAGE_KEY = "cirs-language";

const TRANSLATIONS = {
  en: {
    Dashboard: "Dashboard",
    Reports: "Reports",
    "Map View": "Map View",
    "Report Approvals": "Report Approvals",
    Citizens: "Citizens",
    Staff: "Staff",
    "Account Approvals": "Account Approvals",
    Departments: "Departments",
    Categories: "Categories",
    Notifications: "Notifications",
    Settings: "Settings",
    "Search reports, users…": "Search reports, users…",
    "Language: English": "Language: English",
    "Language: Myanmar": "Language: Myanmar",
    Home: "Home",
    Map: "Map",
    Report: "Report",
    Board: "Board",
    Me: "Me",
    "Hello, {name}": "Hello, {name}",
    "Let's make our community better.": "Let's make our community better.",
    "Your score": "Your score",
    "Report an issue": "Report an issue",
    "Your recent reports": "Your recent reports",
    "No reports yet": "No reports yet",
    "Reports you file will show up here.": "Reports you file will show up here.",
    "Pending approval": "Pending approval",
    Assigned: "Assigned",
    "In progress": "In progress",
    Resolved: "Resolved",
    Closed: "Closed",
    Rejected: "Rejected",
    Pending: "Pending",
    Approved: "Approved",
    Suspended: "Suspended",
    Low: "Low",
    Normal: "Normal",
    High: "High",
    Urgent: "Urgent",
    Electricity: "Electricity",
    Roads: "Roads",
    Water: "Water",
    Sanitation: "Sanitation",
    Parks: "Parks",
    Buildings: "Buildings",
    Other: "Other",
    Unknown: "Unknown",
    "Nothing here yet": "Nothing here yet",
    "No records": "No records",
    Delete: "Delete",
    Cancel: "Cancel",
    Confirm: "Confirm",
    Save: "Save",
    Close: "Close",
    Edit: "Edit",
    Create: "Create",
    Search: "Search",
    Filter: "Filter",
    Loading: "Loading",
    "Loading…": "Loading…",
    "All statuses": "All statuses",
    "Report submitted": "Report submitted",
    Overview: "Overview",
    Timeline: "Timeline",
    Comments: "Comments",
    Resolution: "Resolution",
    Location: "Location",
    Back: "Back",
    "Submit report": "Submit report",
    "Use my location": "Use my location",
    Description: "Description",
    Category: "Category",
    Status: "Status",
    Priority: "Priority",
    Department: "Department",
    Actions: "Actions",
    View: "View",
    Details: "Details",
    "Welcome back": "Welcome back",
    "Log in": "Log in",
    Password: "Password",
    Email: "Email",
    "Create an account": "Create an account",
    "Full name": "Full name",
    Phone: "Phone",
    "Date of birth": "Date of birth",
    "NRC number": "NRC number",
    "Already have an account?": "Already have an account?",
    "New citizen?": "New citizen?",
    "Create account": "Create account",
    "Account created — it's pending admin approval before you can log in.": "Account created — it's pending admin approval before you can log in.",
    "Login to SCIRS to report and track community issues.": "Login to SCIRS to report and track community issues.",
    "Report issues, track their progress, and help your community move forward.": "Report issues, track their progress, and help your community move forward.",
    "Get access to your community hub — report issues and see them through to resolution.": "Get access to your community hub — report issues and see them through to resolution.",
    "Sign up to report issues in your community.": "Sign up to report issues in your community.",
    Leaderboard: "Leaderboard",
    "Community map": "Community map",
    All: "All",
    "View details": "View details",
    Profile: "Profile",
    "Edit profile": "Edit profile",
    "Save changes": "Save changes",
    "New report": "New report",
    History: "History",
    "Your account is awaiting approval": "Your account is awaiting approval",
    "You'll be able to submit reports once an admin approves your account.": "You'll be able to submit reports once an admin approves your account.",
    "Drag the pin, or tap the map, to set the exact spot.": "Drag the pin, or tap the map, to set the exact spot.",
    "Select an option": "Select an option",
    "Loading categories…": "Loading categories…",
    "What's wrong? *": "What's wrong? *",
    "Describe the issue…": "Describe the issue…",
    Photo: "Photo",
    Add: "Add",
    "Remove photo": "Remove photo",
    "Submitting…": "Submitting…",
    "Deleting…": "Deleting…",
    "Since Last Week": "Since Last Week",
    Administrator: "Administrator",
    "Government Staff": "Government Staff",
    "{count} unread notifications": "{count} unread notifications",
    "Status timeline": "Status timeline",
    Name: "Name",
    Submitted: "Submitted",
    Approve: "Approve",
    Deny: "Deny",
    Denied: "Denied",
    "Failed to approve account": "Failed to approve account",
    "Failed to deny account": "Failed to deny account",
    "Loading pending accounts…": "Loading pending accounts…",
    "No accounts waiting": "No accounts waiting",
    "New citizen signups will show up here.": "New citizen signups will show up here.",
    "Account approvals": "Account approvals",
    "New citizen signups waiting for review.": "New citizen signups waiting for review.",
    "Deny account": "Deny account",
    '"{name}" will be notified with the reason below.': '"{name}" will be notified with the reason below.',
    "Reason *": "Reason *",
    "Explain why this account is being denied…": "Explain why this account is being denied…",
    "Denying…": "Denying…",
    "Each category routes reports to a department by default.": "Each category routes reports to a department by default.",
    "New category": "New category",
    "Category updated": "Category updated",
    "Category created": "Category created",
    "Category deleted": "Category deleted",
    "Failed to delete category": "Failed to delete category",
    "No categories yet": "No categories yet",
    "Create a category so citizens have something to select when reporting.":
      "Create a category so citizens have something to select when reporting.",
    Colour: "Colour",
    Active: "Active",
    Inactive: "Inactive",
    "(inactive)": "(inactive)",
    "Edit {name}": "Edit {name}",
    "Delete {name}": "Delete {name}",
    "Delete category": "Delete category",
    'This deactivates "{name}". It will no longer appear in the citizen report form.':
      'This deactivates "{name}". It will no longer appear in the citizen report form.',
    "Edit category": "Edit category",
    "Update this category's details.": "Update this category's details.",
    "Categories route reports to a department on approval.": "Categories route reports to a department on approval.",
    "Name *": "Name *",
    "Department *": "Department *",
    "Select a department": "Select a department",
    Icon: "Icon",
    "Select an icon": "Select an icon",
    "Pin colour": "Pin colour",
    "Use colour {hex}": "Use colour {hex}",
    "Inactive categories no longer appear in the citizen report form.":
      "Inactive categories no longer appear in the citizen report form.",
    "Category active": "Category active",
    "Create category": "Create category",
    "Failed to save category": "Failed to save category",
    "Saving…": "Saving…",
    "Failed to save department": "Failed to save department",
    "All citizen accounts on the platform.": "All citizen accounts on the platform.",
    "Search name or email…": "Search name or email…",
    "Loading citizens…": "Loading citizens…",
    "No citizens found": "No citizens found",
    "Try a different search or status filter.": "Try a different search or status filter.",
    Joined: "Joined",
    "Citizen suspended": "Citizen suspended",
    "Citizen deleted": "Citizen deleted",
    "Action failed": "Action failed",
    "Suspend {name}": "Suspend {name}",
    "Suspend citizen": "Suspend citizen",
    "Delete citizen": "Delete citizen",
    '"{name}" won\'t be able to log in or submit reports until reinstated.':
      '"{name}" won\'t be able to log in or submit reports until reinstated.',
    'This deactivates "{name}"\'s account. Their existing reports are kept.':
      'This deactivates "{name}"\'s account. Their existing reports are kept.',
    Suspend: "Suspend",
    "Suspending…": "Suspending…",
    "The default routing target for report categories.": "The default routing target for report categories.",
    "New department": "New department",
    "Department updated": "Department updated",
    "Department created": "Department created",
    "Department deleted": "Department deleted",
    "Failed to delete department": "Failed to delete department",
    "Loading departments…": "Loading departments…",
    "No departments yet": "No departments yet",
    "Create a department so categories have somewhere to route to.":
      "Create a department so categories have somewhere to route to.",
    "Contact email": "Contact email",
    "Delete department": "Delete department",
    'This deactivates "{name}". Existing categories keep their link to it, but new categories can\'t be created against it until it\'s reactivated.':
      'This deactivates "{name}". Existing categories keep their link to it, but new categories can\'t be created against it until it\'s reactivated.',
    "Edit department": "Edit department",
    "Update this department's details.": "Update this department's details.",
    "Departments are the default routing target for report categories.":
      "Departments are the default routing target for report categories.",
    "Inactive departments can't be assigned to new categories.": "Inactive departments can't be assigned to new categories.",
    "Department active": "Department active",
    "Create department": "Create department",
    "Report approvals": "Report approvals",
    "New citizen reports waiting for review.": "New citizen reports waiting for review.",
    "Loading pending reports…": "Loading pending reports…",
    "No reports waiting": "No reports waiting",
    "New citizen reports will show up here.": "New citizen reports will show up here.",
    Code: "Code",
    Title: "Title",
    Reporter: "Reporter",
    "Failed to approve report": "Failed to approve report",
    "Deny report": "Deny report",
    '"{title}" will be rejected and the reporter notified.': '"{title}" will be rejected and the reporter notified.',
    "Explain why this report is being denied…": "Explain why this report is being denied…",
    "Failed to deny report": "Failed to deny report",
    "Government staff accounts, scoped to one department each.": "Government staff accounts, scoped to one department each.",
    "New staff": "New staff",
    "Loading staff…": "Loading staff…",
    "No staff accounts yet": "No staff accounts yet",
    "Create a staff account so departments have someone assigned.":
      "Create a staff account so departments have someone assigned.",
    "Staff account created": "Staff account created",
    "Create staff account": "Create staff account",
    "Staff accounts are approved immediately and scoped to one department.":
      "Staff accounts are approved immediately and scoped to one department.",
    "Full name *": "Full name *",
    "Email *": "Email *",
    "Temporary password *": "Temporary password *",
    "Failed to create staff account": "Failed to create staff account",
    "Creating…": "Creating…",
    "Recent reports": "Recent reports",
    Reported: "Reported",
    "Staff Dashboard": "Staff Dashboard",
    "Your reports overview and department performance": "Your reports overview and department performance",
    "Total Reports": "Total Reports",
    Remaining: "Remaining",
    "New Today": "New Today",
    "Report locations": "Report locations",
    "Map preview": "Map preview",
    "No data available for the selected period.": "No data available for the selected period.",
    "Monthly reports per department": "Monthly reports per department",
    "Departments handling reports across the city.": "Departments handling reports across the city.",
    "New reports, urgent items, and department mentions for your department.":
      "New reports, urgent items, and department mentions for your department.",
    "Mark all as read": "Mark all as read",
    "Loading notifications…": "Loading notifications…",
    "No notifications yet": "No notifications yet",
    "New reports, urgent items, and mentions for your department will show up here.":
      "New reports, urgent items, and mentions for your department will show up here.",
    "Mark read": "Mark read",
    "just now": "just now",
    "{n}m ago": "{n}m ago",
    "{n}h ago": "{n}h ago",
    "{n}d ago": "{n}d ago",
    "Your account details.": "Your account details.",
    "Failed to save changes": "Failed to save changes",
    "Email and department are managed by an administrator and can't be changed here.":
      "Email and department are managed by an administrator and can't be changed here.",
    "Log out": "Log out",
    "Every report routed through the system.": "Every report routed through the system.",
    "Search title, code…": "Search title, code…",
    "All categories": "All categories",
    "All departments": "All departments",
    "From date": "From date",
    "To date": "To date",
    "Loading reports…": "Loading reports…",
    "No reports found": "No reports found",
    "Try a different search or filter.": "Try a different search or filter.",
    "Showing {start}–{end} of {total}": "Showing {start}–{end} of {total}",
    Previous: "Previous",
    Next: "Next",
    "Report not found": "Report not found",
    "Back to reports": "Back to reports",
    "Priority updated": "Priority updated",
    "Failed to update priority": "Failed to update priority",
    "Assign department": "Assign department",
    "Add comment": "Add comment",
    "Change status": "Change status",
    "Rejection reason: ": "Rejection reason: ",
    "Assigned staff": "Assigned staff",
    "Not yet routed": "Not yet routed",
    Unassigned: "Unassigned",
    "No status changes yet.": "No status changes yet.",
    "No comments yet": "No comments yet",
    "Internal notes for the handling department.": "Internal notes for the handling department.",
    "Add an internal comment…": "Add an internal comment…",
    "Adding…": "Adding…",
    "Failed to add comment": "Failed to add comment",
    "Completion photos": "Completion photos",
    "No completion photos yet": "No completion photos yet",
    "Upload photo evidence before moving this report to Resolved.":
      "Upload photo evidence before moving this report to Resolved.",
    "Uploading…": "Uploading…",
    "Upload photo": "Upload photo",
    "Citizen feedback": "Citizen feedback",
    "No feedback from the citizen yet.": "No feedback from the citizen yet.",
    "Resolution photo uploaded": "Resolution photo uploaded",
    "Failed to upload photo": "Failed to upload photo",
    "Reassign this report to a different department or staff member.":
      "Reassign this report to a different department or staff member.",
    "Staff member": "Staff member",
    "Failed to reassign report": "Failed to reassign report",
    "Save assignment": "Save assignment",
    "This report has no further status changes available.": "This report has no further status changes available.",
    "Currently {status}.": "Currently {status}.",
    "New status": "New status",
    Remarks: "Remarks",
    "Optional note for the citizen's timeline…": "Optional note for the citizen's timeline…",
    "Completion photo *": "Completion photo *",
    "Required to move a report to Resolved (ui-rules.md).": "Required to move a report to Resolved (ui-rules.md).",
    "Attach a completion photo before resolving.": "Attach a completion photo before resolving.",
    "Failed to change status": "Failed to change status",
    "Save status": "Save status",
    "All priorities": "All priorities",
    "Report code": "Report code",
    "View full report": "View full report",
    "Report detail": "Report detail",
    "Back to your reports": "Back to your reports",
    "Reason: ": "Reason: ",
    "Resolution photo": "Resolution photo",
    "Issues you report will show up here with their status and history.":
      "Issues you report will show up here with their status and history.",
    "Your feedback": "Your feedback",
    "How did we do?": "How did we do?",
    "{n} star": "{n} star",
    "{n} stars": "{n} stars",
    "Comment (optional)": "Comment (optional)",
    "Submit feedback": "Submit feedback",
    "Show password": "Show password",
    "Hide password": "Hide password",
    "Streetlight out": "Streetlight out",
    "Power outage": "Power outage",
    "Exposed wiring": "Exposed wiring",
    Pothole: "Pothole",
    "Blocked drain": "Blocked drain",
    "Damaged sidewalk": "Damaged sidewalk",
    "Water leak": "Water leak",
    "No water supply": "No water supply",
    Flooding: "Flooding",
    "Overflowing bin": "Overflowing bin",
    "Illegal dumping": "Illegal dumping",
    "Missed collection": "Missed collection",
    "Damaged equipment": "Damaged equipment",
    "Overgrown area": "Overgrown area",
    Litter: "Litter",
    "Structural damage": "Structural damage",
    "Broken fixture": "Broken fixture",
    Graffiti: "Graffiti",
    "General issue": "General issue",
  },
  my: {
    Dashboard: "ဒက်ရှ်ဘုတ်",
    Reports: "တိုင်ကြားချက်များ",
    "Map View": "မြေပုံကြည့်ရန်",
    "Report Approvals": "တိုင်ကြားချက် အတည်ပြုခြင်း",
    Citizens: "ပြည်သူများ",
    Staff: "ဝန်ထမ်းများ",
    "Account Approvals": "အကောင့် အတည်ပြုခြင်း",
    Departments: "ဌာနများ",
    Categories: "အမျိုးအစားများ",
    Notifications: "အသိပေးချက်များ",
    Settings: "ဆက်တင်များ",
    "Search reports, users…": "တိုင်ကြားချက်များ၊ အသုံးပြုသူများ ရှာရန်…",
    "Language: English": "ဘာသာစကား: အင်္ဂလိပ်",
    "Language: Myanmar": "ဘာသာစကား: မြန်မာ",
    Home: "ပင်မ",
    Map: "မြေပုံ",
    Report: "တိုင်ကြားရန်",
    Board: "အဆင့်စာရင်း",
    Me: "ကျွန်ုပ်",
    "Hello, {name}": "မင်္ဂလာပါ၊ {name}",
    "Let's make our community better.": "ကျွန်ုပ်တို့၏ ရပ်ရွာကို ပိုမိုကောင်းမွန်အောင် အတူတကွလုပ်ဆောင်ကြပါစို့။",
    "Your score": "သင့်အမှတ်",
    "Report an issue": "ပြဿနာတိုင်ကြားရန်",
    "Your recent reports": "သင့်၏ လတ်တလောတိုင်ကြားချက်များ",
    "No reports yet": "တိုင်ကြားချက် မရှိသေးပါ",
    "Reports you file will show up here.": "သင်တင်ပြသော တိုင်ကြားချက်များကို ဤနေရာတွင် တွေ့ရပါမည်။",
    "Pending approval": "အတည်ပြုရန် စောင့်ဆိုင်းနေသည်",
    Assigned: "တာဝန်ပေးအပ်ပြီး",
    "In progress": "ဆောင်ရွက်နေသည်",
    Resolved: "ဖြေရှင်းပြီး",
    Closed: "ပိတ်သိမ်းပြီး",
    Rejected: "ပယ်ချပြီး",
    Pending: "စောင့်ဆိုင်းနေသည်",
    Approved: "အတည်ပြုပြီး",
    Suspended: "ဆိုင်းငံ့ထားသည်",
    Low: "နိမ့်",
    Normal: "ပုံမှန်",
    High: "မြင့်",
    Urgent: "အရေးပေါ်",
    Electricity: "လျှပ်စစ်",
    Roads: "လမ်းများ",
    Water: "ရေ",
    Sanitation: "သန့်ရှင်းရေး",
    Parks: "ပန်းခြံများ",
    Buildings: "အဆောက်အအုံများ",
    Other: "အခြား",
    Unknown: "မသိရှိပါ",
    "Nothing here yet": "ဤနေရာတွင် မရှိသေးပါ",
    "No records": "မှတ်တမ်း မရှိပါ",
    Delete: "ဖျက်မည်",
    Cancel: "ပယ်ဖျက်မည်",
    Confirm: "အတည်ပြုမည်",
    Save: "သိမ်းမည်",
    Close: "ပိတ်မည်",
    Edit: "ပြင်ဆင်မည်",
    Create: "ဖန်တီးမည်",
    Search: "ရှာဖွေမည်",
    Filter: "စစ်ထုတ်မည်",
    Loading: "ဖတ်ရှုနေသည်",
    "Loading…": "ဖတ်ရှုနေသည်…",
    "All statuses": "အခြေအနေအားလုံး",
    "Report submitted": "တိုင်ကြားချက် တင်ပြပြီး",
    Overview: "အကျဉ်းချုပ်",
    Timeline: "မှတ်တမ်းအချိန်လိုင်း",
    Comments: "မှတ်ချက်များ",
    Resolution: "ဖြေရှင်းချက်",
    Location: "တည်နေရာ",
    Back: "နောက်သို့",
    "Submit report": "တိုင်ကြားချက် တင်မည်",
    "Use my location": "ကျွန်ုပ်၏တည်နေရာကို အသုံးပြုမည်",
    Description: "ဖော်ပြချက်",
    Category: "အမျိုးအစား",
    Status: "အခြေအနေ",
    Priority: "ဦးစားပေး",
    Department: "ဌာန",
    Actions: "လုပ်ဆောင်ချက်များ",
    View: "ကြည့်မည်",
    Details: "အသေးစိတ်",
    "Welcome back": "ပြန်လည်ကြိုဆိုပါသည်",
    "Log in": "ဝင်ရောက်မည်",
    Password: "စကားဝှက်",
    Email: "အီးမေးလ်",
    "Create an account": "အကောင့်ဖန်တီးမည်",
    "Full name": "အမည်အပြည့်အစုံ",
    Phone: "ဖုန်း",
    "Date of birth": "မွေးသက္ကရာဇ်",
    "NRC number": "မှတ်ပုံတင်အမှတ်",
    "Already have an account?": "အကောင့်ရှိပြီးသားလား",
    "New citizen?": "နိုင်ငံသားအသစ်လား",
    "Create account": "အကောင့်ဖန်တီးမည်",
    "Account created — it's pending admin approval before you can log in.": "အကောင့်ဖန်တီးပြီးပါပြီ — ဝင်ရောက်နိုင်ရန် စီမံခန့်ခွဲသူ၏ အတည်ပြုချက်ကို စောင့်ရပါမည်။",
    "Login to SCIRS to report and track community issues.": "SCIRS သို့ ဝင်ရောက်ပြီး ရပ်ရွာပြဿနာများကို တိုင်ကြားခြင်းနှင့် စောင့်ကြည့်ခြင်း ပြုလုပ်ပါ။",
    "Report issues, track their progress, and help your community move forward.": "ပြဿနာများကို တိုင်ကြားပါ၊ တိုးတက်မှုကို စောင့်ကြည့်ပါ၊ သင့်ရပ်ရွာ တိုးတက်ရေးတွင် ပါဝင်ပါ။",
    "Get access to your community hub — report issues and see them through to resolution.": "သင့်ရပ်ရွာဝန်ဆောင်မှုသို့ ဝင်ရောက်ပြီး ပြဿနာများကို တိုင်ကြားကာ ဖြေရှင်းသည်အထိ စောင့်ကြည့်ပါ။",
    "Sign up to report issues in your community.": "သင့်ရပ်ရွာရှိ ပြဿနာများကို တိုင်ကြားရန် အကောင့်ဖွင့်ပါ။",
    Leaderboard: "အဆင့်စာရင်း",
    "Community map": "ရပ်ရွာမြေပုံ",
    All: "အားလုံး",
    "View details": "အသေးစိတ်ကြည့်မည်",
    Profile: "ကိုယ်ရေးအချက်အလက်",
    "Edit profile": "ကိုယ်ရေးအချက်အလက် ပြင်ဆင်မည်",
    "Save changes": "ပြောင်းလဲမှုများ သိမ်းမည်",
    "New report": "တိုင်ကြားချက်အသစ်",
    History: "မှတ်တမ်း",
    "Your account is awaiting approval": "သင့်အကောင့်သည် အတည်ပြုချက်ကို စောင့်ဆိုင်းနေပါသည်",
    "You'll be able to submit reports once an admin approves your account.": "စီမံခန့်ခွဲသူက သင့်အကောင့်ကို အတည်ပြုပြီးနောက် တိုင်ကြားချက်များ တင်ပြနိုင်ပါမည်။",
    "Drag the pin, or tap the map, to set the exact spot.": "ပင်ကို ဆွဲရွှေ့ပါ သို့မဟုတ် မြေပုံကိုနှိပ်၍ တိကျသောနေရာကို သတ်မှတ်ပါ။",
    "Select an option": "ရွေးချယ်ပါ",
    "Loading categories…": "အမျိုးအစားများ ဖတ်ရှုနေသည်…",
    "What's wrong? *": "ဘာဖြစ်နေပါသလဲ။ *",
    "Describe the issue…": "ပြဿနာကို ဖော်ပြပါ…",
    Photo: "ဓာတ်ပုံ",
    Add: "ထည့်မည်",
    "Remove photo": "ဓာတ်ပုံ ဖယ်ရှားမည်",
    "Submitting…": "တင်ပြနေသည်…",
    "Deleting…": "ဖျက်နေသည်…",
    "Since Last Week": "ပြီးခဲ့သည့်အပတ်မှစ၍",
    Administrator: "စီမံခန့်ခွဲသူ",
    "Government Staff": "အစိုးရဝန်ထမ်း",
    "{count} unread notifications": "မဖတ်ရသေးသော အသိပေးချက် {count} ခု",
    "Status timeline": "အခြေအနေ မှတ်တမ်းအချိန်လိုင်း",
    Name: "အမည်",
    Submitted: "တင်ပြသည့်ရက်",
    Approve: "အတည်ပြုမည်",
    Deny: "ငြင်းပယ်မည်",
    Denied: "ငြင်းပယ်ပြီး",
    "Failed to approve account": "အကောင့်ကို အတည်ပြုခြင်း မအောင်မြင်ပါ",
    "Failed to deny account": "အကောင့်ကို ငြင်းပယ်ခြင်း မအောင်မြင်ပါ",
    "Loading pending accounts…": "အတည်ပြုရန် စောင့်နေသော အကောင့်များ ဖတ်ရှုနေသည်…",
    "No accounts waiting": "စောင့်ဆိုင်းနေသော အကောင့် မရှိပါ",
    "New citizen signups will show up here.": "ပြည်သူအသစ် အကောင့်ဖွင့်မှုများကို ဤနေရာတွင် တွေ့ရပါမည်။",
    "Account approvals": "အကောင့် အတည်ပြုခြင်းများ",
    "New citizen signups waiting for review.": "စစ်ဆေးရန် စောင့်နေသော ပြည်သူအသစ် အကောင့်ဖွင့်မှုများ။",
    "Deny account": "အကောင့် ငြင်းပယ်မည်",
    '"{name}" will be notified with the reason below.': '"{name}" သည် အောက်ပါအကြောင်းရင်းဖြင့် အသိပေးချက် ရရှိပါမည်။',
    "Reason *": "အကြောင်းရင်း *",
    "Explain why this account is being denied…": "ဤအကောင့်ကို အဘယ်ကြောင့် ငြင်းပယ်ရသည်ကို ရှင်းပြပါ…",
    "Denying…": "ငြင်းပယ်နေသည်…",
    "Each category routes reports to a department by default.":
      "အမျိုးအစားတစ်ခုစီသည် ပုံသေအားဖြင့် တိုင်ကြားချက်များကို ဌာနတစ်ခုသို့ လမ်းကြောင်းပြသည်။",
    "New category": "အမျိုးအစားအသစ်",
    "Category updated": "အမျိုးအစား အပ်ဒိတ်လုပ်ပြီး",
    "Category created": "အမျိုးအစား ဖန်တီးပြီး",
    "Category deleted": "အမျိုးအစား ဖျက်ပြီး",
    "Failed to delete category": "အမျိုးအစား ဖျက်ခြင်း မအောင်မြင်ပါ",
    "No categories yet": "အမျိုးအစား မရှိသေးပါ",
    "Create a category so citizens have something to select when reporting.":
      "ပြည်သူများ တိုင်ကြားချက်တင်သည့်အခါ ရွေးချယ်စရာရှိရန် အမျိုးအစားတစ်ခု ဖန်တီးပါ။",
    Colour: "အရောင်",
    Active: "အသုံးပြုနေဆဲ",
    Inactive: "အသုံးမပြုတော့ပါ",
    "(inactive)": "(အသုံးမပြုတော့ပါ)",
    "Edit {name}": "{name} ကို ပြင်ဆင်မည်",
    "Delete {name}": "{name} ကို ဖျက်မည်",
    "Delete category": "အမျိုးအစား ဖျက်မည်",
    'This deactivates "{name}". It will no longer appear in the citizen report form.':
      '"{name}" ကို အသုံးမပြုတော့အောင် ပြုလုပ်ပါမည်။ ၎င်းသည် ပြည်သူ့တိုင်ကြားချက် ဖောင်တွင် နောက်ထပ် ပေါ်လာမည် မဟုတ်ပါ။',
    "Edit category": "အမျိုးအစား ပြင်ဆင်မည်",
    "Update this category's details.": "ဤအမျိုးအစား၏ အသေးစိတ်အချက်အလက်များကို အပ်ဒိတ်လုပ်ပါ။",
    "Categories route reports to a department on approval.":
      "အတည်ပြုပြီးနောက် အမျိုးအစားများသည် တိုင်ကြားချက်များကို ဌာနတစ်ခုသို့ လမ်းကြောင်းပြသည်။",
    "Name *": "အမည် *",
    "Department *": "ဌာန *",
    "Select a department": "ဌာနတစ်ခု ရွေးချယ်ပါ",
    Icon: "အိုင်ကွန်",
    "Select an icon": "အိုင်ကွန်တစ်ခု ရွေးချယ်ပါ",
    "Pin colour": "ပင်၏အရောင်",
    "Use colour {hex}": "{hex} အရောင်ကို သုံးမည်",
    "Inactive categories no longer appear in the citizen report form.":
      "အသုံးမပြုတော့သော အမျိုးအစားများသည် ပြည်သူ့တိုင်ကြားချက် ဖောင်တွင် ပေါ်လာမည် မဟုတ်ပါ။",
    "Category active": "အမျိုးအစား အသုံးပြုနေဆဲ",
    "Create category": "အမျိုးအစား ဖန်တီးမည်",
    "Failed to save category": "အမျိုးအစား သိမ်းဆည်းခြင်း မအောင်မြင်ပါ",
    "Saving…": "သိမ်းဆည်းနေသည်…",
    "Failed to save department": "ဌာန သိမ်းဆည်းခြင်း မအောင်မြင်ပါ",
    "All citizen accounts on the platform.": "ပလက်ဖောင်းပေါ်ရှိ ပြည်သူ့အကောင့်အားလုံး။",
    "Search name or email…": "အမည် သို့မဟုတ် အီးမေးလ် ရှာဖွေပါ…",
    "Loading citizens…": "ပြည်သူများ ဖတ်ရှုနေသည်…",
    "No citizens found": "ပြည်သူ မတွေ့ပါ",
    "Try a different search or status filter.": "အခြားရှာဖွေမှု သို့မဟုတ် အခြေအနေစစ်ထုတ်မှုကို စမ်းကြည့်ပါ။",
    Joined: "ပါဝင်သည့်ရက်",
    "Citizen suspended": "ပြည်သူ့အကောင့် ဆိုင်းငံ့ပြီး",
    "Citizen deleted": "ပြည်သူ့အကောင့် ဖျက်ပြီး",
    "Action failed": "လုပ်ဆောင်ချက် မအောင်မြင်ပါ",
    "Suspend {name}": "{name} ကို ဆိုင်းငံ့မည်",
    "Suspend citizen": "ပြည်သူ့အကောင့် ဆိုင်းငံ့မည်",
    "Delete citizen": "ပြည်သူ့အကောင့် ဖျက်မည်",
    '"{name}" won\'t be able to log in or submit reports until reinstated.':
      '"{name}" ကို ပြန်လည်ရေးသွင်းသည်အထိ ဝင်ရောက်ခြင်း သို့မဟုတ် တိုင်ကြားချက် တင်ခြင်း မပြုလုပ်နိုင်ပါ။',
    'This deactivates "{name}"\'s account. Their existing reports are kept.':
      '"{name}" ၏ အကောင့်ကို အသုံးမပြုတော့အောင် ပြုလုပ်ပါမည်။ ၎င်း၏ ရှိပြီးသား တိုင်ကြားချက်များကို ဆက်လက်ထိန်းသိမ်းထားပါမည်။',
    Suspend: "ဆိုင်းငံ့မည်",
    "Suspending…": "ဆိုင်းငံ့နေသည်…",
    "The default routing target for report categories.": "တိုင်ကြားချက် အမျိုးအစားများအတွက် ပုံသေ လမ်းကြောင်းပြရာနေရာ။",
    "New department": "ဌာနအသစ်",
    "Department updated": "ဌာန အပ်ဒိတ်လုပ်ပြီး",
    "Department created": "ဌာန ဖန်တီးပြီး",
    "Department deleted": "ဌာန ဖျက်ပြီး",
    "Failed to delete department": "ဌာန ဖျက်ခြင်း မအောင်မြင်ပါ",
    "Loading departments…": "ဌာနများ ဖတ်ရှုနေသည်…",
    "No departments yet": "ဌာန မရှိသေးပါ",
    "Create a department so categories have somewhere to route to.":
      "အမျိုးအစားများ လမ်းကြောင်းပြရန် နေရာရှိစေရန် ဌာနတစ်ခု ဖန်တီးပါ။",
    "Contact email": "ဆက်သွယ်ရန် အီးမေးလ်",
    "Delete department": "ဌာန ဖျက်မည်",
    'This deactivates "{name}". Existing categories keep their link to it, but new categories can\'t be created against it until it\'s reactivated.':
      '"{name}" ကို အသုံးမပြုတော့အောင် ပြုလုပ်ပါမည်။ ရှိပြီးသား အမျိုးအစားများသည် ၎င်းနှင့် ဆက်စပ်မှုကို ဆက်လက်ထားရှိမည်ဖြစ်သော်လည်း ပြန်လည်အသက်သွင်းသည်အထိ ဌာနအသစ်များကို ၎င်းနှင့် ချိတ်ဆက်၍ မဖန်တီးနိုင်ပါ။',
    "Edit department": "ဌာန ပြင်ဆင်မည်",
    "Update this department's details.": "ဤဌာန၏ အသေးစိတ်အချက်အလက်များကို အပ်ဒိတ်လုပ်ပါ။",
    "Departments are the default routing target for report categories.":
      "ဌာနများသည် တိုင်ကြားချက် အမျိုးအစားများအတွက် ပုံသေ လမ်းကြောင်းပြရာနေရာများ ဖြစ်သည်။",
    "Inactive departments can't be assigned to new categories.": "အသုံးမပြုတော့သော ဌာနများကို အမျိုးအစားအသစ်များအတွက် တာဝန်ပေးအပ်၍ မရပါ။",
    "Department active": "ဌာန အသုံးပြုနေဆဲ",
    "Create department": "ဌာန ဖန်တီးမည်",
    "Report approvals": "တိုင်ကြားချက် အတည်ပြုခြင်းများ",
    "New citizen reports waiting for review.": "စစ်ဆေးရန် စောင့်နေသော ပြည်သူ့တိုင်ကြားချက်အသစ်များ။",
    "Loading pending reports…": "အတည်ပြုရန် စောင့်နေသော တိုင်ကြားချက်များ ဖတ်ရှုနေသည်…",
    "No reports waiting": "စောင့်ဆိုင်းနေသော တိုင်ကြားချက် မရှိပါ",
    "New citizen reports will show up here.": "ပြည်သူ့တိုင်ကြားချက်အသစ်များကို ဤနေရာတွင် တွေ့ရပါမည်။",
    Code: "ကုဒ်",
    Title: "ခေါင်းစဉ်",
    Reporter: "တိုင်ကြားသူ",
    "Failed to approve report": "တိုင်ကြားချက်ကို အတည်ပြုခြင်း မအောင်မြင်ပါ",
    "Deny report": "တိုင်ကြားချက် ငြင်းပယ်မည်",
    '"{title}" will be rejected and the reporter notified.': '"{title}" ကို ပယ်ချပြီး တိုင်ကြားသူအား အသိပေးပါမည်။',
    "Explain why this report is being denied…": "ဤတိုင်ကြားချက်ကို အဘယ်ကြောင့် ငြင်းပယ်ရသည်ကို ရှင်းပြပါ…",
    "Failed to deny report": "တိုင်ကြားချက်ကို ငြင်းပယ်ခြင်း မအောင်မြင်ပါ",
    "Government staff accounts, scoped to one department each.":
      "အစိုးရဝန်ထမ်းအကောင့်များ၊ တစ်ဦးစီလျှင် ဌာနတစ်ခုသာ သတ်မှတ်ထားသည်။",
    "New staff": "ဝန်ထမ်းအသစ်",
    "Loading staff…": "ဝန်ထမ်းများ ဖတ်ရှုနေသည်…",
    "No staff accounts yet": "ဝန်ထမ်းအကောင့် မရှိသေးပါ",
    "Create a staff account so departments have someone assigned.":
      "ဌာနများတွင် တာဝန်ခံတစ်ဦး ရှိစေရန် ဝန်ထမ်းအကောင့်တစ်ခု ဖန်တီးပါ။",
    "Staff account created": "ဝန်ထမ်းအကောင့် ဖန်တီးပြီး",
    "Create staff account": "ဝန်ထမ်းအကောင့် ဖန်တီးမည်",
    "Staff accounts are approved immediately and scoped to one department.":
      "ဝန်ထမ်းအကောင့်များကို ချက်ချင်း အတည်ပြုပြီး ဌာနတစ်ခုသာ သတ်မှတ်ပေးသည်။",
    "Full name *": "အမည်အပြည့်အစုံ *",
    "Email *": "အီးမေးလ် *",
    "Temporary password *": "ယာယီစကားဝှက် *",
    "Failed to create staff account": "ဝန်ထမ်းအကောင့် ဖန်တီးခြင်း မအောင်မြင်ပါ",
    "Creating…": "ဖန်တီးနေသည်…",
    "Recent reports": "လတ်တလော တိုင်ကြားချက်များ",
    Reported: "တိုင်ကြားသည့်ရက်",
    "Staff Dashboard": "ဝန်ထမ်း ဒက်ရှ်ဘုတ်",
    "Your reports overview and department performance": "သင့်တိုင်ကြားချက် ခြုံငုံသုံးသပ်ချက်နှင့် ဌာန၏ လုပ်ဆောင်ချက်",
    "Total Reports": "စုစုပေါင်း တိုင်ကြားချက်များ",
    Remaining: "ကျန်ရှိနေသည်",
    "New Today": "ယနေ့ အသစ်",
    "Report locations": "တိုင်ကြားချက် တည်နေရာများ",
    "Map preview": "မြေပုံ အကြိုကြည့်ရှုမှု",
    "No data available for the selected period.": "ရွေးချယ်ထားသော ကာလအတွက် ဒေတာ မရရှိပါ။",
    "Monthly reports per department": "ဌာနတစ်ခုစီ၏ လစဉ်တိုင်ကြားချက်များ",
    "Departments handling reports across the city.": "မြို့တစ်လျှောက် တိုင်ကြားချက်များကို ကိုင်တွယ်နေသော ဌာနများ။",
    "New reports, urgent items, and department mentions for your department.":
      "သင့်ဌာနအတွက် တိုင်ကြားချက်အသစ်များ၊ အရေးကြီးအချက်များနှင့် ဌာနအမှတ်တံဆိပ်များ။",
    "Mark all as read": "အားလုံးကို ဖတ်ပြီးအဖြစ် သတ်မှတ်မည်",
    "Loading notifications…": "အသိပေးချက်များ ဖတ်ရှုနေသည်…",
    "No notifications yet": "အသိပေးချက် မရှိသေးပါ",
    "New reports, urgent items, and mentions for your department will show up here.":
      "သင့်ဌာနအတွက် တိုင်ကြားချက်အသစ်များ၊ အရေးကြီးအချက်များနှင့် အမှတ်တံဆိပ်များကို ဤနေရာတွင် တွေ့ရပါမည်။",
    "Mark read": "ဖတ်ပြီးဟု သတ်မှတ်မည်",
    "just now": "ယခုလေးတင်",
    "{n}m ago": "{n} မိနစ်က",
    "{n}h ago": "{n} နာရီက",
    "{n}d ago": "{n} ရက်က",
    "Your account details.": "သင့်အကောင့် အသေးစိတ်အချက်အလက်များ။",
    "Failed to save changes": "ပြောင်းလဲမှုများ သိမ်းဆည်းခြင်း မအောင်မြင်ပါ",
    "Email and department are managed by an administrator and can't be changed here.":
      "အီးမေးလ်နှင့် ဌာနကို စီမံခန့်ခွဲသူက ကိုင်တွယ်ပြီး ဤနေရာတွင် ပြောင်းလဲ၍ မရပါ။",
    "Log out": "ထွက်မည်",
    "Every report routed through the system.": "စနစ်မှတစ်ဆင့် လမ်းကြောင်းပြထားသော တိုင်ကြားချက်အားလုံး။",
    "Search title, code…": "ခေါင်းစဉ်၊ ကုဒ် ရှာဖွေပါ…",
    "All categories": "အမျိုးအစားအားလုံး",
    "All departments": "ဌာနအားလုံး",
    "From date": "မှစသည့်ရက်",
    "To date": "ထိရက်",
    "Loading reports…": "တိုင်ကြားချက်များ ဖတ်ရှုနေသည်…",
    "No reports found": "တိုင်ကြားချက် မတွေ့ပါ",
    "Try a different search or filter.": "အခြားရှာဖွေမှု သို့မဟုတ် စစ်ထုတ်မှုကို စမ်းကြည့်ပါ။",
    "Showing {start}–{end} of {total}": "{total} ထဲမှ {start}–{end} ကို ပြသနေသည်",
    Previous: "ယခင်",
    Next: "နောက်တစ်ခု",
    "Report not found": "တိုင်ကြားချက် မတွေ့ပါ",
    "Back to reports": "တိုင်ကြားချက်များသို့ ပြန်သွားရန်",
    "Priority updated": "ဦးစားပေးအဆင့် အပ်ဒိတ်လုပ်ပြီး",
    "Failed to update priority": "ဦးစားပေးအဆင့် အပ်ဒိတ်လုပ်ခြင်း မအောင်မြင်ပါ",
    "Assign department": "ဌာန တာဝန်ပေးမည်",
    "Add comment": "မှတ်ချက် ထည့်မည်",
    "Change status": "အခြေအနေ ပြောင်းမည်",
    "Rejection reason: ": "ပယ်ချသည့်အကြောင်းရင်း: ",
    "Assigned staff": "တာဝန်ပေးထားသော ဝန်ထမ်း",
    "Not yet routed": "လမ်းကြောင်းမပြရသေးပါ",
    Unassigned: "တာဝန်မပေးရသေးပါ",
    "No status changes yet.": "အခြေအနေ ပြောင်းလဲမှု မရှိသေးပါ။",
    "No comments yet": "မှတ်ချက် မရှိသေးပါ",
    "Internal notes for the handling department.": "ကိုင်တွယ်နေသော ဌာနအတွက် အတွင်းရေးမှတ်ချက်များ။",
    "Add an internal comment…": "အတွင်းရေး မှတ်ချက် ထည့်ပါ…",
    "Adding…": "ထည့်နေသည်…",
    "Failed to add comment": "မှတ်ချက် ထည့်ခြင်း မအောင်မြင်ပါ",
    "Completion photos": "ပြီးစီးမှု ဓာတ်ပုံများ",
    "No completion photos yet": "ပြီးစီးမှု ဓာတ်ပုံ မရှိသေးပါ",
    "Upload photo evidence before moving this report to Resolved.":
      "ဤတိုင်ကြားချက်ကို ဖြေရှင်းပြီးအဖြစ် ပြောင်းမည်မတိုင်မီ ဓာတ်ပုံသက်သေ တင်ပါ။",
    "Uploading…": "တင်နေသည်…",
    "Upload photo": "ဓာတ်ပုံ တင်မည်",
    "Citizen feedback": "ပြည်သူ့ အကြံပြုချက်",
    "No feedback from the citizen yet.": "ပြည်သူထံမှ အကြံပြုချက် မရှိသေးပါ။",
    "Resolution photo uploaded": "ဖြေရှင်းမှု ဓာတ်ပုံ တင်ပြီး",
    "Failed to upload photo": "ဓာတ်ပုံ တင်ခြင်း မအောင်မြင်ပါ",
    "Reassign this report to a different department or staff member.":
      "ဤတိုင်ကြားချက်ကို အခြားဌာန သို့မဟုတ် ဝန်ထမ်းတစ်ဦးထံ ပြန်လည်တာဝန်ပေးပါ။",
    "Staff member": "ဝန်ထမ်း",
    "Failed to reassign report": "တိုင်ကြားချက် ပြန်လည်တာဝန်ပေးခြင်း မအောင်မြင်ပါ",
    "Save assignment": "တာဝန်ပေးမှု သိမ်းမည်",
    "This report has no further status changes available.": "ဤတိုင်ကြားချက်တွင် နောက်ထပ် အခြေအနေပြောင်းလဲမှု မရှိတော့ပါ။",
    "Currently {status}.": "လက်ရှိ {status}။",
    "New status": "အခြေအနေအသစ်",
    Remarks: "မှတ်ချက်",
    "Optional note for the citizen's timeline…": "ပြည်သူ၏ အချိန်ဇယားအတွက် ရွေးချယ်နိုင်သော မှတ်စု…",
    "Completion photo *": "ပြီးစီးမှု ဓာတ်ပုံ *",
    "Required to move a report to Resolved (ui-rules.md).": "တိုင်ကြားချက်ကို ဖြေရှင်းပြီးအဖြစ် ပြောင်းရန် လိုအပ်သည်။",
    "Attach a completion photo before resolving.": "ဖြေရှင်းခြင်းမပြုမီ ပြီးစီးမှုဓာတ်ပုံ တစ်ပုံ ပူးတွဲပါ။",
    "Failed to change status": "အခြေအနေ ပြောင်းလဲခြင်း မအောင်မြင်ပါ",
    "Save status": "အခြေအနေ သိမ်းမည်",
    "All priorities": "ဦးစားပေးအဆင့်အားလုံး",
    "Report code": "တိုင်ကြားချက် ကုဒ်",
    "View full report": "တိုင်ကြားချက် အပြည့်အစုံ ကြည့်မည်",
    "Report detail": "တိုင်ကြားချက် အသေးစိတ်",
    "Back to your reports": "သင့်တိုင်ကြားချက်များသို့ ပြန်သွားရန်",
    "Reason: ": "အကြောင်းရင်း: ",
    "Resolution photo": "ဖြေရှင်းမှု ဓာတ်ပုံ",
    "Issues you report will show up here with their status and history.":
      "သင်တိုင်ကြားသော ပြဿနာများကို ၎င်းတို့၏ အခြေအနေနှင့် မှတ်တမ်းများနှင့်အတူ ဤနေရာတွင် တွေ့ရပါမည်။",
    "Your feedback": "သင့် အကြံပြုချက်",
    "How did we do?": "ကျွန်ုပ်တို့ ဘယ်လိုလုပ်ခဲ့သလဲ။",
    "{n} star": "{n} ကြယ်",
    "{n} stars": "{n} ကြယ်များ",
    "Comment (optional)": "မှတ်ချက် (ရွေးချယ်နိုင်သည်)",
    "Submit feedback": "အကြံပြုချက် တင်မည်",
    "Show password": "စကားဝှက် ပြမည်",
    "Hide password": "စကားဝှက် ဝှက်မည်",
    "Streetlight out": "လမ်းမီး ပျက်နေသည်",
    "Power outage": "လျှပ်စစ် ပြတ်တောက်မှု",
    "Exposed wiring": "ကြိုးဖေါ်ထုတ်နေမှု",
    Pothole: "လမ်းတွင်း ပေါက်ကြားနေမှု",
    "Blocked drain": "မိလ္လာပိတ်ဆို့နေမှု",
    "Damaged sidewalk": "လူသွားလမ်း ပျက်စီးနေမှု",
    "Water leak": "ရေယိုစိမ့်မှု",
    "No water supply": "ရေမရှိခြင်း",
    Flooding: "ရေကြီးမှု",
    "Overflowing bin": "အမှိုက်ပုံး ပြည့်လျှံနေမှု",
    "Illegal dumping": "တရားမဝင် အမှိုက်ပစ်ချခြင်း",
    "Missed collection": "အမှိုက်စုဆောင်းမှု ကျန်ခဲ့ခြင်း",
    "Damaged equipment": "ပစ္စည်းကိရိယာ ပျက်စီးနေမှု",
    "Overgrown area": "မြက်ပင် အလွန်ကြီးထွားနေသောနေရာ",
    Litter: "အမှိုက်များ",
    "Structural damage": "အဆောက်အအုံ ပျက်စီးမှု",
    "Broken fixture": "ပစ္စည်း ကျိုးပဲ့နေမှု",
    Graffiti: "နံရံပန်းချီ ရေးဆွဲမှု",
    "General issue": "ယေဘုယျ ပြဿနာ",
  },
};

export function LanguageProvider({ children, defaultLanguage = "en" }) {
  const [language, setLanguage] = useState(() => {
    const stored = localStorage.getItem(STORAGE_KEY);
    return stored === "my" || stored === "en" ? stored : defaultLanguage;
  });

  useEffect(() => {
    document.documentElement.lang = language === "my" ? "my" : "en";
    document.documentElement.dataset.language = language;
    localStorage.setItem(STORAGE_KEY, language);

    document.body.classList.remove("language-transition");
    requestAnimationFrame(() => document.body.classList.add("language-transition"));
    const timer = window.setTimeout(() => document.body.classList.remove("language-transition"), 180);
    return () => window.clearTimeout(timer);
  }, [language]);

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      t: (key, values = {}) =>
        (TRANSLATIONS[language][key] ?? key).replace(/\{(\w+)\}/g, (_, name) => values[name] ?? `{${name}}`),
    }),
    [language]
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (ctx) return ctx;

  return {
    language: "en",
    setLanguage: () => {},
    t: (key, values = {}) =>
      (TRANSLATIONS.en[key] ?? key).replace(/\{(\w+)\}/g, (_, name) => values[name] ?? `{${name}}`),
  };
}